### ISSUE TITLE
Cluster creation often timeout waiting for Argo CD or Vault

### ISSUE THREAD

**Issue by fharper** [konstructio/kubefirst#2233]
### Which version of kubefirst are you using?

2.4.11

### Which cloud provider?

None specific

### Which DNS?

None specific

### Which installation type?

None specific

### Which distributed Git provider?

None specific

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

None specific

### What is the issue?

No matter the cloud (I tried k3d, Civo, DigitalOcean), the Git provider (I tried GitHub & GitLab) or if the installation is done with the CLI or the UI (I tried both), the cluster creation often fail waiting for Argo CD or at the Vault step. I have this issue for at least 2-3 months now, but now I'm not the only ones. Most of the team can replicate, and our community users also.

It is not a Docker resources limitation as I only run kubefirst on Docker when I create a cluster, and my resources are way higher than the kubefirst minimum requirements: 8 CPU, 16GB of memory, 2GB for swap, 104GB of virtual disk (never using more than half). My internet connection is around 656/53Mbps so more than sufficient also.

I would be happy to try to debug to find what would be the issue as I know not everyone is able to replicate, so it may be specific to my machine/configurations or others are just lucky to never hit this case.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
When it timeout on Vault, here is the error + the state of the cluster (see no Vault pod at all yet).

![CleanShot 2024-07-08 at 14 56 24@2x](https://github.com/kubefirst/kubefirst/assets/1170989/31731712-288b-4429-9a35-b60bc9c5e4ae)

![CleanShot 2024-07-08 at 14 56 42@2x](https://github.com/kubefirst/kubefirst/assets/1170989/e2ab13f6-d225-403f-840e-142428e820cb)

**Comment by fharper** [comment]
It may be useful information, but Argo CD or Vault never time out when creating a cluster on K3s, while with k3d + public clouds, I get timeout 4+ out of 5 times...

k3d resources cannot be changed, but I'm starting to wonder if it may be about the default instances for public clouds kubefirst is creating when I use the CLI, and the default selected one when I use the UI. Food for thoughts.

**Comment by fharper** [comment]
While writing my previous comment, I just remembered that @jokestax may have found the issue, and shared this with us during's today standup. I don't remember all the details, but it is not timing out: in the case of Argo CD, there are another error (I think it's not being deployed), which isn't raised. Not sure about Vault.

@jokestax, unless you are coming with a fix now, can you add some details on your discovery so we have some history, and people stumbling on this issue have more context until we fix it please.

**Comment by jokestax** [comment]
@fharper ,issue is with the argocd-applicationset-controller,if you check logs of that deployment,it says "secret-key" missing

**Comment by fharper** [comment]
This [PR](https://github.com/kubefirst/kubefirst-api/pull/363) will fix the issue for public clouds, but not k3d. Maybe once we remove runtime in favor of the API, k3d timeout won't be a problem anymore.
