### ISSUE TITLE
developer group in vault can't edit their own password - should be allowed

### ISSUE THREAD

**Issue by johndietz** [konstructio/kubefirst#2265]
### Which version of kubefirst are you using?

2.4.17

### Which cloud provider?

Civo

### Which DNS?

None specific

### Which installation type?

None specific

### Which distributed Git provider?

None specific

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

macOS

### What is the issue?

developers should be free to reset their own passwords in vault. admins can. developers get the following error:
![image](https://github.com/user-attachments/assets/0e3ea133-c993-4e3a-a4b9-7520ecdc4265)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
@jarededwards fix this in our management cluster, so we can replicate what he did there.
