### ISSUE TITLE
kubefirst reset needs to be more aggressive with its cleanup

### ISSUE THREAD

**Issue by johndietz** [konstructio/kubefirst#2272]
### What is your feature idea?

in the community and internally, kubefirst users are familiarizing themselves with 
`rm -rf ~/.kubefirst ~/.k1`
to do a kubefirst reset on their local environment. we have a `kubefirst reset` command that we don't trust internally and that the community doesn't trust because it tries too hard to keep things that nobody needs. we need `kubefirst reset` to delete the `~/.k1` folder and the ~/.kubefirst` file, in full, without asking or apologizing.

### Why is it needed?

![CleanShot 2024-08-28 at 21 04 02@2x](https://github.com/user-attachments/assets/cf4ca6d0-e2c0-40e2-8c0a-47d875f297f4)

### Is this missing feature preventing you from using kubefirst?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
Status update: it's still being worked on.
