### ISSUE TITLE
error finding Vault StatefulSet

### ISSUE THREAD

**Issue by sadaramk** [konstructio/kubefirst#2324]
### Which version of kubefirst are you using?

v2.7.4

### Which cloud provider?

k3d (local)

### Which DNS?

None specific

### Which installation type?

CLI

### Which distributed Git provider?

GitHub

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

macOS

### What is the issue?

Fresh installation fails with the below error.

Error: error finding Vault StatefulSet: the StatefulSet "vault" in Namespace "vault" was not created within the timeout period: timed out waiting for the condition
Error occurred during command execution: error finding Vault StatefulSet: the StatefulSet "vault" in Namespace "vault" was not created within the timeout period: timed out waiting for the condition
If a detailed error message was available, please make the necessary corrections before retrying.
You can re-run the last command to try the operation again.

<img width="949" alt="image" src="https://github.com/user-attachments/assets/727e7d0f-6677-4226-b2d1-405d5ade5f83">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by patrickdappollonio** [comment]
Hello!

Would you mind sharing the output of "kubectl get pods -A"?

**Comment by sadaramk** [comment]
<img width="846" alt="image" src="https://github.com/user-attachments/assets/27640f58-a128-44c2-819d-9f749a40da5b">

**Comment by patrickdappollonio** [comment]
Huh, it doesn't seem that Vault was even launched in your cluster. 

In the `~/.k1` folder there should be some logs, can you share them?

**Comment by sadaramk** [comment]
here is the log, I will try and clear everything and try one more time

<img width="1089" alt="image" src="https://github.com/user-attachments/assets/6039b9e8-b4f5-41f4-a602-13b8d2ffc5f2">

**Comment by patrickdappollonio** [comment]
Didn't add much details unfortunately. 

Do you have a statefulset deployment for Vault? I suspect not.

There's an ArgoCD pod, if you portforward it, you can look in ArgoCD what happened that the next "wave" of applications didn't install. The user is `admin` and the password is in the secret called `initial-admin-secret`.

**Comment by sadaramk** [comment]
I noticed some other behaviours on my Mac, so closing this issue for now as the issue could be at my end. Thank you for your prompt response, @patrickdappollonio. I appreciate it.

**Comment by patrickdappollonio** [comment]
No problem! If you face this same issue flow again, please let us know. We would love to lend a hand troubleshooting what the issue could've been.
