### ISSUE TITLE
Installed apps not shown on local setup with new kubefirst version

### ISSUE THREAD

**Issue by danielschlegel** [konstructio/kubefirst#2331]
### Which version of kubefirst are you using?

2.7.5

### Which cloud provider?

k3d (local)

### Which DNS?

None specific

### Which installation type?

CLI

### Which distributed Git provider?

GitLab

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

macOS

### What is the issue?

When i access https://kubefirst.kubefirst.dev/dashboard/applications i do not see the apps anymore. 

Cluster was created like this. With earlier version this worked but fetching credentials was broken. Thats why i did update.

```
kubefirst k3d create \
  --git-provider gitlab \
  --gitlab-group kubefirst-group \
  --cluster-name kubefirst-cluster 
```
  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
@danielschlegel thanks for reporting this issue, we will try to replicate and understand what is happening here.

**Comment by fharper** [comment]
We were able to identify the issue. The fix will be available with the next Kubefirst release. Sorry about that, and thanks again for reporting it. In the meantime, you can always try with another cloud as the issue shouldn't be elsewhere. If you want, I would love to send you some swag as a small thank you gesture: if so, hit me up on our [Slack community](https://konstruct.io/slack) (I'm Fred) or [email me](mailto:fred@konstruct.io).

**Comment by jokestax** [comment]
@danielschlegel we have made the new release which fixes the bug

**Comment by danielschlegel** [comment]
Thanks a lot for this instant fix!
